"""
Data models for the RAG ingestion pipeline.
Defines the core entities used in the system.
"""

from dataclasses import dataclass
from typing import List, Dict, Optional
from datetime import datetime


@dataclass
class TextChunk:
    """
    A segment of extracted content from a book page.
    """
    id: str
    content: str
    source_url: str
    page_title: str
    section_heading: str
    chunk_index: int
    hash: str

    def __post_init__(self):
        """Validate the TextChunk after initialization."""
        if not self.content.strip():
            raise ValueError("Content must not be empty")

        if not self.source_url:
            raise ValueError("Source URL must be provided")


@dataclass
class EmbeddingVector:
    """
    A numerical representation of text content generated by Cohere models.
    """
    vector_id: str
    embedding: List[float]  # List of float values representing the vector
    text_chunk_id: str
    metadata: Dict[str, str]  # Contains source_url, page_title, section_heading, chunk_index

    def __post_init__(self):
        """Validate the EmbeddingVector after initialization."""
        if not self.embedding:
            raise ValueError("Embedding must not be empty")

        required_metadata = ['source_url', 'page_title', 'section_heading', 'chunk_index']
        for key in required_metadata:
            if key not in self.metadata:
                raise ValueError(f"Required metadata field '{key}' is missing")


@dataclass
class CrawledPage:
    """
    A web page from the Docusaurus book that has been processed.
    """
    url: str
    title: str
    content: str
    section_hierarchy: List[str]
    status: str  # success, error, etc.
    crawled_at: datetime
    page_id: Optional[str] = None

    def __post_init__(self):
        """Validate the CrawledPage after initialization."""
        if not self.url:
            raise ValueError("URL must be provided")

        valid_statuses = ['pending', 'crawling', 'success', 'error', 'timeout']
        if self.status not in valid_statuses:
            raise ValueError(f"Status must be one of {valid_statuses}")


@dataclass
class VectorCollection:
    """
    A logical grouping in Qdrant containing related embedding vectors.
    """
    name: str
    size: int
    created_at: datetime
    book_source: str

    def __post_init__(self):
        """Validate the VectorCollection after initialization."""
        if not self.name:
            raise ValueError("Name must be provided")


@dataclass
class ProcessingJob:
    """
    Represents a single execution of the ingestion pipeline.
    """
    id: str
    source_url: str
    status: str  # pending, running, completed, failed
    started_at: datetime
    pages_processed: int = 0
    chunks_created: int = 0
    vectors_stored: int = 0
    completed_at: Optional[datetime] = None
    error_message: Optional[str] = None

    def __post_init__(self):
        """Validate the ProcessingJob after initialization."""
        valid_statuses = ['pending', 'running', 'completed', 'failed']
        if self.status not in valid_statuses:
            raise ValueError(f"Status must be one of {valid_statuses}")

        if self.status == 'completed' and self.completed_at is None:
            raise ValueError("Completed jobs must have a completed_at timestamp")