"""
Data models for agent interactions in the RAG system.
"""
from dataclasses import dataclass
from typing import List, Optional
from datetime import datetime


@dataclass
class AgentQuery:
    """
    Input query submitted to the RAG agent for processing.

    Attributes:
        query_text: Natural language question or query from user
        user_selected_text: Additional context provided by user (optional)
        timestamp: When the query was submitted
        request_id: Unique identifier for tracking the request
    """
    query_text: str
    user_selected_text: Optional[str] = None
    timestamp: datetime = None
    request_id: str = ""

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()


@dataclass
class RetrievedChunk:
    """
    Individual text chunk retrieved from the Qdrant collection.

    Attributes:
        text: The actual content of the chunk
        source_url: URL where the content originated
        position: Position of chunk in original document
        score: Semantic similarity score (0.0-1.0)
        chunk_id: Unique identifier for the chunk
        created_at: Timestamp when chunk was indexed
    """
    text: str
    source_url: str
    position: int
    score: float
    chunk_id: str
    created_at: float


@dataclass
class RetrievedContext:
    """
    Context retrieved from Qdrant based on semantic similarity to the query.

    Attributes:
        chunks: List of relevant text chunks with metadata
        query_embedding: Vector representation of the query
        retrieval_time: Time taken to retrieve context in seconds
        total_chunks_found: Total number of chunks found before filtering
    """
    chunks: List[RetrievedChunk]
    query_embedding: Optional[List[float]] = None
    retrieval_time: float = 0.0
    total_chunks_found: int = 0


@dataclass
class GroundedResponse:
    """
    Response generated by the agent that is grounded in retrieved context.

    Attributes:
        answer: The final answer generated by the agent
        confidence_score: Confidence level in the response quality
        sources_used: List of source URLs used in the response
        processing_time: Total time taken to generate response
        grounding_validation_passed: Whether response passed grounding checks
    """
    answer: str
    confidence_score: float
    sources_used: List[str]
    processing_time: float
    grounding_validation_passed: bool = True


@dataclass
class AgentToolCall:
    """
    Record of tools called by the agent during response generation.

    Attributes:
        tool_name: Name of the tool called (e.g., "retrieval_tool")
        input_parameters: Parameters passed to the tool
        result: Result returned by the tool
        execution_time: Time taken to execute the tool call
    """
    tool_name: str
    input_parameters: dict
    result: any
    execution_time: float